In [3]:
import pandas as pd 
import numpy as np

In [4]:
RickMort = pd.read_csv("RickAndMortyScripts.csv")
RickMort.rename(columns={"episode name":"episode_name"},inplace=True)
RickMort.head()

,index,season no.,episode no.,episode_name,name,line
0,0,1,1,Pilot,Rick,Morty! You gotta come on. Jus'... you gotta co...
1,2,1,1,Pilot,Rick,"I got a surprise for you, Morty."
2,4,1,1,Pilot,Rick,"Come on, I got a surprise for you. Come on, h..."
3,6,1,1,Pilot,Rick,"We gotta go, gotta get outta here, come on. Go..."
4,7,1,1,Pilot,Rick,"What do you think of this... flying vehicle, M..."

In [8]:
Rick = RickMort[RickMort.name == "Rick"]
Morty = RickMort[RickMort.name == "Morty"]
Rick.head()
Morty.head()
Rick = pd.DataFrame(Rick)
Rick.size
Morty.size

0

In [9]:
Simpsons_script_lines = pd.read_csv("simpsons_script_lines.csv")
Simpsons_script_lines.head()

,id,episode_id,number,raw_text,timestamp_in_ms,speaking_line,character_id,location_id,raw_character_text,raw_location_text,spoken_words,normalized_text,word_count
0,9549,32,209,"Miss Hoover: No, actually, it was a little of ...",848000,True,464.0,3.0,Miss Hoover,Springfield Elementary School,"No, actually, it was a little of both. Sometim...",no actually it was a little of both sometimes ...,31
1,9550,32,210,Lisa Simpson: (NEAR TEARS) Where's Mr. Bergstrom?,856000,True,9.0,3.0,Lisa Simpson,Springfield Elementary School,Where's Mr. Bergstrom?,wheres mr bergstrom,3
2,9551,32,211,Miss Hoover: I don't know. Although I'd sure l...,856000,True,464.0,3.0,Miss Hoover,Springfield Elementary School,I don't know. Although I'd sure like to talk t...,i dont know although id sure like to talk to h...,22
3,9552,32,212,Lisa Simpson: That life is worth living.,864000,True,9.0,3.0,Lisa Simpson,Springfield Elementary School,That life is worth living.,that life is worth living,5
4,9553,32,213,Edna Krabappel-Flanders: The polls will be ope...,864000,True,40.0,3.0,Edna Krabappel-Flanders,Springfield Elementary School,The polls will be open from now until the end ...,the polls will be open from now until the end ...,33

In [10]:
Homer = RickMort[RickMort.name == "Rick"]